name: Hello world workflow

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Run script test.sh'
      run: test.sh
      shell: bash
