name: Hello world workflow

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Grab and set up variable'
      run: echo "RTEST=${{ secrets.SSH_PRIVATE_KEY }}" >> $GITHUB_ENV
    - name: 'Run script test.sh'
      run: bash ./.github/workflows/test.sh
